### ISSUE TITLE
How to create custom token

### ISSUE THREAD

**Issue by freudmaster** [expl/rs-firebase-admin-sdk#14]
Hello, first of all thank you for the work you made on this library, I want to create a custom token after creating a user in my firebase rust backend app how could I manage it ?
Thank you for you response

**Comment by expl** [comment]
Hey,

Custom tokens under the hood are actually not handled directly by Firebase but by Google IAM API ([signJwt](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signJwt) to be specific). Because of this, it is not supported using Firebase emulator making this tricky to properly test it and a major reason why I haven't done it so far.

Your best bet would be to use the API directly by either calling REST/gRPC directly or using a wrapper crate like [google-api-proto](https://mechiru.github.io/google-api-proto/google_api_proto/google/iam/credentials/v1/index.html) and verify them with a generic JWT token verification crate like [jwt-simple](https://crates.io/crates/jwt-simple).

I might add this later as am optional feature to this crate as well.

Best of luck!

**Comment by freudmaster** [comment]
Okay thank you
